include:
  - .ci/ci-files/*.yaml

stages:
  - build
  - deploy

.build_template:
  stage: build
  allow_failure: false
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_IMAGE_TAG: "${CI_PIPELINE_IID}"
    DOCKER_KEEP_LOCAL_TAGS: 5
    DOCKER_BUILD_CONTEXT: "."
    DOCKER_FILE_PATH: "./.ci/Dockerfile"
    DOCKER_BUILD_ARGS: ""
  before_script:
    - docker login --username=${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - export DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-"gitlab.smartpricing.btc-s.ru:5555/o.kravchuk/${CI_PROJECT_NAME}"}
    - export DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG:-"${CI_PIPELINE_IID}"}
    - >
      docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ${DOCKER_BUILD_CONTEXT}
      --file ${DOCKER_FILE_PATH}
      ${DOCKER_BUILD_ARGS}
    - docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
  after_script:
    - >-
      docker images -q --filter reference="${DOCKER_IMAGE_NAME}:*" |
      tail -n +$(($DOCKER_KEEP_LOCAL_TAGS+1)) |
      xargs -r docker rmi -f || true
    - docker builder prune -f
  tags:
    - oleg-build

.deploy-app:
  stage: deploy
  before_script:
    - docker rm -f `docker ps -a --no-trunc | grep ${DOCKER_IMAGE_NAME} | awk '{ print $1}'` 2> /dev/null || true
  script:
    - |
        docker run -d \
        --name ${CI_PROJECT_NAME}-${PROJ} \
        --net=${DOCKER_NET} \
        -v /etc/localtime:/etc/localtime \
        --restart always \
        --env-file .env \
        ${DOCKER_IMAGE_NAME}:${{DOCKER_IMAGE_TAG}
  tags:
    - oleg-deploy


