server:
  port: ${PORT:8080}
  url: ${SERVER_URL:http://localhost:8080}
#  servlet:
#    context-path: /api
spring:
  codec:
    max-in-memory-size: 10MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  profiles:
    active: ${ACTIVE_PROFILE:local}

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 2000
  liquibase:
    change-log: classpath:db/master.changelog.yaml
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
custom:
  jwt:
    secret: yourSecretKeyNeedsToBeLongEnoughUEUEUEUEUEUEUE01
    expiration: 86400000
logging:
  file:
    path: logs