build-app:dev:
  extends:
    - .build-app
  only:
    - develop
  variables:
    EXTENTIONS_ARGS: -DGITLAB_DEPLOY_TOKEN=${PACKAGE_REGISTRY_DEPLOY_TOKEN}
  when: always

deploy-app:dev:
  extends:
    - .deploy-app
  variables:
    NAME: api-study-financial
    EXT_PORT: 8086
    DB_NAME: financial
    DB_PASS: financial
    DB_USER: financial
    SERVER_URL: 51.250.81.198
    DOCKER_NET: worker
  dependencies:
    - build-app:dev
  needs:
    - job: build-app:dev
      artifacts: true
  only:
    - develop

