build-app:dev:
  extends:
    - .build_template
  only:
    - develop
  variables:
    EXTENTIONS_ARGS: -DGITLAB_DEPLOY_TOKEN=${PACKAGE_REGISTRY_DEPLOY_TOKEN}
  when: always

deploy-app:dev:
  extends:
    - .deploy-app
  variables:
    NAME: api-study-financial
    DOCKER_NET: dev
    PROJ: develop
  only:
    - develop

